spring:
  profiles: eurekatwo
server:
  port: 4003
eureka:  
  instance:
    appname: etwo
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: false    
    serviceUrl:
      defaultZone: http://localhost:4002/eureka/,http://localhost:4004/eureka/
