spring:
  profiles: eurekaone
server:
  port: 4002  
eureka:
  instance:
    hostname: localhost
    appname: eone
  client:    
    fetch-registry: false
    register-with-eureka: false    
    serviceUrl:
      defaultZone: http://localhost:4002/eureka/
